AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 2.6
# Tests can be long.
Metrics/BlockLength:
  Enabled: false
# Methods can have many parameters.
Metrics/ParameterLists:
  Enabled: false